### ISSUE TITLE
Allow for dynamic setter function

### ISSUE THREAD

**Issue by twolfson** [ejci/favico.js#54]
I am interested in using `favico.js` for `slack-for-linux` to indicate unseen notifications. It would be used in the tray icon and possibly taskbar icon. Currently `favico.js` doesn't support this because it can only set against `elementId` or a `<link>` it creates.

To support this functionality, I suggest adding a new option which is a `setter` callback (i.e. a function that is run every time the image changes). With an integration into `node-webkit`, it would look like:

```js
var favicon = new Favico({
  setter: function (png) {
    tray.icon = png;
  }
});
```

**Comment by twolfson** [comment]
This has fallen quiet but it sounds like we are going to add it. I will speed it up by submitting a PR.

**Comment by twolfson** [comment]
As mentioned in #55, the solution proposed/implemented wasn't fully minded about the problem. While we have a mechanism for setting to an arbitrary location, there is no mechanism for getting from an arbitrary location.

I got a workaround working for [`node-webkit`][] which involves creating a `link` inside of the `browser` context. However, we should consider the broader case (e.g. what if someone is in a `node` only context and wants to use [`node-canvas`][]?

[`node-webkit`]: https://github.com/rogerwang/node-webkit
[`node-canvas`]: https://github.com/Automattic/node-canvas

> For anyone curious about the `node-webkit` implementation, see https://github.com/twolfson/slack-for-linux/blob/e62e33210eba10bace0737433865eb9e1909f00d/app/js/index.js#L53-L84

**Comment by twolfson** [comment]
Any feedback on this?

**Comment by twolfson** [comment]
It has been 2 months since this issue was initially opened. Still looking for feedback on the approach. Thoughts?

**Comment by ejci** [comment]
Hi. Sorry for replying so late. I will merge it. I think its a good idea to have "setter" function. 
I would like to keep it as small as possible so Im not sure If I will add anything to support running it in node-canvas (or something similar)... but I will think about it.

**Comment by twolfson** [comment]
I looked back over my past implementation. It feels hacky because I had to create a link so that the `href` could be pulled out of it. The `getter` support adds a couple of lines and is much less of a hack. I am going to add it in and we can discuss further in the PR =)

**Comment by twolfson** [comment]
Never mind, I am realizing how ingrained we are with HTML element for now. Going to reduce back to `opt.setter`.

**Comment by twolfson** [comment]
I keep on waffling on `getter` in my head. I am going to open another issue for discussion.
