### ISSUE TITLE
Angular JS Demo not working

### ISSUE THREAD

**Issue by dszymczuk** [ejci/favico.js#61]
http://lab.ejci.net/favico.js/example-angular/

Not found http://lab.ejci.net/favico.js/example-angular/favico-0.3.5.min.js

**Comment by escapedcat** [comment]
Cool, just wanted to mention the same :P

**Comment by ejci** [comment]
Yep. I was rearranging folders and files and I forgot to change the path. Fix is on the way...

**Comment by ejci** [comment]
Fixed

**Comment by sebastianfdez** [comment]
Hey! The source of the Angular Demo is down
