### ISSUE TITLE
Incorrect error thow

### ISSUE THREAD

**Issue by amurchick** [ejci/favico.js#67]
In code used:
```javascript
throw 'Too many badges requests in queue.';
```
In `catch` used:
```javascript
throw 'Error setting badge. Message: ' + e.message;
```

When `Too many badges` happens - console output:
```
Uncaught Error setting badge. Message: undefined
```

Needs change code to:
```javascript
throw new Error('Too many badges requests in queue.');
```
or
```javascript
throw 'Error setting badge. Message: ' + (e.message ? e.message : e);
```

**Comment by ejci** [comment]
Good catch. My bad. I will fix it in next release.

**Comment by PrakashPaul** [comment]
I need help to under stand why there is a check for 
if (_queue.length > 100) {
throw new Error('Too many badges requests in queue.');
}
what if queue lenght is more then 100 ? example chat application user getting more then 100 messges......
