### ISSUE TITLE
npm package?

### ISSUE THREAD

**Issue by nchase** [ejci/favico.js#69]
I see that you have an npm-style package.json – are you open to publishing this repository on npm?

**Comment by ejci** [comment]
You can find favico.js on bower. But if you feel that it will be also good in npm feel free to push the change.

**Comment by nchase** [comment]
I published the current version. It is here: https://www.npmjs.com/package/favico.js

I tried adding you as a maintainer of the package (after which I planned to remove myself), but `ejci` doesn't appear to be a user at the npmjs.com registry.

Are you registered there under a different name, or have you not registered?

Here's the info for registering: https://docs.npmjs.com/cli/adduser

If/when you are registered, you can easily publish new versions by just running `npm publish`.

I should have checked to see if you had an account on NPM before attempting to publish the package.

Let me know if you want me to _delete_ the package on npm  – that's easy to do too.

**Comment by ejci** [comment]
Thanks for looking into it.
I think it will be easier if you remove it and I will add it again. It will be easier for future version.

**Comment by ejci** [comment]
Will you remove it from the npm registry?
Because I will need to run `npm publish` after each release and if Im not the owner it will not work.

**Comment by nchase** [comment]
> Will you remove it from the npm registry?
> Because I will need to run npm publish after each release and if Im not the owner it will not work.

I just ran `npm unpublish` but the repo is still showing up on NPM. maybe it's cached, I'll check back in a few minutes to make sure it's gone.

**Comment by nchase** [comment]
looks like it's gone, go for it!

**Comment by ejci** [comment]
I tried to publish it... 
It looks like its there but for some reason it does not have readme and `npm publish` gave me few errors...
```
$ npm publish
npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "publish"
npm ERR! node v0.12.1
npm ERR! npm  v2.7.5
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/favico.js?write=true
npm ERR! 404
npm ERR! 404 'favico.js' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     ~/favico.js_0.3.x/npm-debug.log
```
https://www.npmjs.com/package/favico.js

Will check later if its a cache/conflict issue or not (with your previous version). If yes I will bump the version to 0.3.8 and publish it during the weekend.

**Comment by ejci** [comment]
And its out: https://www.npmjs.com/package/favico.js

**Comment by nchase** [comment]
Awesome! Thank you.
