### ISSUE TITLE
Icons vs badge

### ISSUE THREAD

**Issue by char0n** [ejci/favico.js#74]
This is maybe more a question than a bug. I have been trying everything, but nothing seems to work.

First I will explain what is expected behavior:

0.) set badge
1.) change the icon, bud preserve the badge
2.) show badge on top of changed icon
3.) change the icon to original, bud preserve the badge
4.) continue the loop from the 0.)

My code looks like this:

HTML:
<link rel="icon" href="assets/favicon.ico" />

JavaScript:
var favico = new Favico();
changeFaviconEventHandler = function(img) {
  favico.image(img);
};
changeBadgeEventHandler = function(number) {
  favico.badge(number);
};

The actual behavior is this:

Whenever I call favico.image(img), badge is lost. Whenever I call favico.badge(number) icon is resetted to the original icon, that was there when the page loaded and badge information is shown on top of it.

Am I missing something or my expected behavior is not possible using this library ?

Thanks a lot.

**Comment by ejci** [comment]
You are not missing anything. Its expected.

Its not possible to have custom image and badge on it in the same time. 
Badge is always rendered on top of favicon default image.

**Comment by char0n** [comment]
Even if the custom image is also ICO format file ?

**Comment by ejci** [comment]
Even then. Thats the way how it works now.
Feel free to create a patch to make it work like you want.

**Comment by char0n** [comment]
Ok thanks, I used https://github.com/tommoor/tinycon which is referenced from your project, that does exactly what I need.
