### ISSUE TITLE
SecurityError in Chrome 43.0.2357.81 on Windows 8.1

### ISSUE THREAD

**Issue by EpicWumbo2048** [ejci/favico.js#77]
To recreate:
  run Chrome 43.0.2357.81 on Windows 8.1 Pro
  browse to some web page which has a <canvas>
  in console:
    new Favico()

Error received:
  Uncaught SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Stack trace:
  L.setIcon
  M.reset
  M.ready
  a.hasAttribute.c.onload

**Comment by ejci** [comment]
This kind of security error you will get when favicon image is on different domain then the script is running (for example its on CDN). If the image doesn't not have proper response header ``` Access-Control-Allow-Origin: * ``` browsers will block access to that image.


You can read more about CORS here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS

Let me know if you have more questions.

**Comment by EpicWumbo2048** [comment]
This occurs before I specify an image. I fully intend to give it an image on the same domain, but I get this security error before I even specify one. I'm rather confident that this is a bug and is worth fixing.

**Comment by ejci** [comment]
Can you share a code sample? Or a link?
