### ISSUE TITLE
Dirty indicator instead of number?

### ISSUE THREAD

**Issue by migig** [ejci/favico.js#79]
Is there a way to superimpose a dirty indicator (e.g. a small dot / circle) instead of a number?

There is an icon font option, but that is too complicated for something so simple. Then there is the option of showing a symbol, but the `Favico` object only accepts numbers.

Is there a way to do this?

**Comment by ejci** [comment]
Currently now. But feel free to push the change.
You can use the same background/font color and it will show you "dot" (but I guess you want something smaller)

**Comment by migig** [comment]
@ejci Excellent idea! Thanks! :beer:
