### ISSUE TITLE
TypeError: this is undefined

### ISSUE THREAD

**Issue by migig** [ejci/favico.js#81]
I'm getting the error `TypeError: this is undefined` because of the very last block of code in the library:

````javascript
// included directly via <script> tag
	else {
		this.Favico = Favico;   // <------ BUG
	}
````

If `this` is replaced with `window`, then it works.

**Comment by ejci** [comment]
Can you share more code? Because its hard to tell whats wrong your example.
Also dont forget that "this" is depended on context https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

**Comment by ejci** [comment]
Ah my bad. The code sample is from the lib. Can you share how you are using it in your code?

**Comment by migig** [comment]
@ejci Yes I'm using it exactly like in the docs. If I don't use it, I still get this error - I get the error just by including the library.

I was thinking that maybe it's a conflict with another library, but I'm not sure. It's weird that no one else has reported this error.

But it's definitely the source of the error, in my case.

**Comment by ejci** [comment]
Thats really weird... because if the script is just included it should run in window context and this should be window.
Something weird is happening there...
Try to remove libraries one by one to see what is causing it. Or if you have a link I can check the code and maybe I can help.

**Comment by migig** [comment]
@ejci Good idea! I will do that and let you know of the results. Thanks for your advice!

**Comment by migig** [comment]
I discovered the problem. There was a "use strict;" being added when my scripts were being concatenated. And this caused the favico.js script to break badly. Not sure why though, because it already runs in strict mode.

But, the `use strict` is inside the `Favico` function, and the problem was outside, in the AMD/CommonJS/ScriptTag declarations. Maybe it should be moved out into the module level.

Anyway, thanks for your advice. It's an excellent library! :smile:
