### ISSUE TITLE
Position not respected when using animation to update badge

### ISSUE THREAD

**Issue by gary-teamwork** [ejci/favico.js#91]
Noticed on chrome/firefox latest stable that when we update the badge value using an animation, after animation ends, the red circle is at the 'bottom' position whereas we had set the position to be top.

This is particularly prevalent when the favicon is being displayed on the browser tab that is not the current active tab in the browser.

**Comment by acg** [comment]
I can confirm this issue. When the tab has focus, position is respected. When the tab doesn't have focus, no animation happens, and the badge is placed at bottom even if you're using `position: "up"`.

**Comment by ejci** [comment]
Thats very strange. I will try to look into it.

**Comment by acg** [comment]
Patch incoming.

**Comment by ejci** [comment]
@acg :+1:
