### ISSUE TITLE
TypeError: _img.attachEvent is not a function

### ISSUE THREAD

**Issue by pandersson06** [ejci/favico.js#94]
Hi, after the latest commit, I get this error on my server. 
"TypeError: _img.attachEvent is not a function /node_modules/favico.js/favico.js:152"

latest commit "45004bf714a903ac7d4a2140dc9067b2ce818c7f"

Don't know if I need to change something on my server or if its a bug in favico.

**Comment by ejci** [comment]
My bad. I reverted it.

**Comment by pandersson06** [comment]
It works now again. Thanks.
